# Escenario de huecos: aleatorios
gaps:
  name: "random"
  type: "random"

  # Configuraci칩n de huecos aleatorios
  config:
    missing_rates: [0.05, 0.10, 0.20, 0.30, 0.40, 0.50]  # % de datos faltantes
    n_trials: 10  # Repeticiones por cada tasa

    # Distribuci칩n de huecos
    gap_distribution: "uniform"  # ["uniform", "clustered"]

    # Estratificaci칩n temporal
    stratify_by_season: false
    stratify_by_year: false

  # Semilla
  random_seed: 42

  # Guardado de m치scaras
  save_masks: true
  output_dir: "data/processed/gaps/random"
